/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pooii;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Programa extends javax.swing.JFrame {
    
    ManipuladorArquivo ma = new ManipuladorArquivo();      

    /**
     * Creates new form Programa
     */
    public Programa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jTextFieldDesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCadastrarFuncionario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNomeC = new javax.swing.JTextField();
        jTextFieldCpfC = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDataC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIdC = new javax.swing.JTextField();
        jTextFieldDesdeC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jButtonListarFuncionario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLista = new javax.swing.JTable();
        jButtonListarCliente = new javax.swing.JButton();
        jButtonListarOrdem = new javax.swing.JButton();
        jButtonSelecionarCliente = new javax.swing.JButton();
        jButtonSelecionarFuncionario = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonGerarOrdem = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldDefeito = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldPecas = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldServico = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldDesconto = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelValorTotal = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jLabelFuncionario = new javax.swing.JLabel();
        jLabelCargo = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jComboBoxSolucionado = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Funcionário");

        jLabel6.setText("Nome:");

        jLabel7.setText("CPF:");

        jLabel8.setText("Data de Nascimento:");

        jLabel1.setText("Cargo:");

        jLabel2.setText("Desde:");

        jButtonCadastrarFuncionario.setText("Cadastrar Funcionário");
        jButtonCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCargo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrarFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cliente");

        jLabel10.setText("Nome:");

        jLabel11.setText("CPF:");

        jLabel12.setText("Data de Nascimento:");

        jLabel3.setText("Identificador:");

        jLabel4.setText("Desde:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Carro");

        jLabel14.setText("Placa");

        jLabel15.setText("Modelo");

        jLabel16.setText("Cor");

        jButtonCadastrarCliente.setText("Cadastrar Cliente");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldIdC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldDesdeC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextFieldDataC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesdeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Lista de Clientes");

        jButtonListarFuncionario.setText("Listar Funcionário");
        jButtonListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarFuncionarioActionPerformed(evt);
            }
        });

        jTableLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableLista);

        jButtonListarCliente.setText("Listar Cliente");
        jButtonListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarClienteActionPerformed(evt);
            }
        });

        jButtonListarOrdem.setText("Listar Ordem de Serviço");
        jButtonListarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarOrdemActionPerformed(evt);
            }
        });

        jButtonSelecionarCliente.setText("Selecionar Cliente");
        jButtonSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarClienteActionPerformed(evt);
            }
        });

        jButtonSelecionarFuncionario.setText("Selecionar Funcionário");
        jButtonSelecionarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarFuncionarioActionPerformed(evt);
            }
        });

        jLabel17.setText("Funcionário:");

        jLabel19.setText("Cargo:");

        jLabel20.setText("Cliente:");

        jLabel22.setText("CPF:");

        jButtonGerarOrdem.setText("Gerar Ordem de Serviço");
        jButtonGerarOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarOrdemActionPerformed(evt);
            }
        });

        jLabel21.setText("Descrição do Defeito:");

        jLabel23.setText("Solucionado:");

        jLabel24.setText("Peças:");

        jLabel25.setText("Mão de Obra:");

        jLabel26.setText("Desconto:");

        jLabel27.setText("Valor Total:");

        jLabel28.setText("R$");

        jLabelValorTotal.setText("0.000,00");

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jComboBoxSolucionado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Nao" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelValorTotal))
                            .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jButtonGerarOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jButtonListarFuncionario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonListarCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                            .addComponent(jButtonListarOrdem))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonSelecionarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel19))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCargo)
                                        .addComponent(jLabelFuncionario))))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonSelecionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel22))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCpf)
                                        .addComponent(jLabelCliente))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addComponent(jLabel21)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jTextFieldPecas, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldServico, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldDefeito, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jComboBoxSolucionado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarFuncionario)
                    .addComponent(jButtonListarCliente)
                    .addComponent(jButtonListarOrdem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelecionarFuncionario)
                    .addComponent(jButtonSelecionarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jLabelFuncionario)
                    .addComponent(jLabelCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(jLabelCargo)
                    .addComponent(jLabelCpf))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDefeito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSolucionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPecas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabelValorTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcular)
                    .addComponent(jButtonGerarOrdem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarFuncionarioActionPerformed
       if( jTextFieldNome.getText().isEmpty() || jTextFieldCpf.getText().isEmpty() || jTextFieldData.getText().isEmpty() || 
               jTextFieldCargo.getText().isEmpty() || jTextFieldDesde.getText().isEmpty() )
        JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos para efetuar o cadastro!");
       else{
           try {
            Funcionario fn = new Funcionario(jTextFieldNome.getText() ,jTextFieldCpf.getText(), jTextFieldData.getText());
            fn.setCargo(jTextFieldCargo.getText());
            fn.setData_funcionario(jTextFieldDesde.getText());
            
            String palavra = fn.getNome()+","+fn.getCpf()+","+fn.getData_nascimento()+","+fn.getCargo()+","+fn.getData_funcionario()+",";
            ma.escritor(palavra, 1);
            
            tabelaFuncionario();
            
            jTextFieldNome.setText("");
            jTextFieldCpf.setText("");
            jTextFieldData.setText("");
            jTextFieldCargo.setText("");
            jTextFieldDesde.setText("");
            
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
       }
    }//GEN-LAST:event_jButtonCadastrarFuncionarioActionPerformed

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
        if( jTextFieldNomeC.getText().isEmpty() || jTextFieldCpfC.getText().isEmpty() || jTextFieldDataC.getText().isEmpty() || 
                jTextFieldIdC.getText().isEmpty() || jTextFieldDesdeC.getText().isEmpty() || jTextFieldPlaca.getText().isEmpty() || 
                jTextFieldModelo.getText().isEmpty() || jTextFieldCor.getText().isEmpty() )
        JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos para efetuar o cadastro!");
       else{
        try {
            Carro ca = new Carro(jTextFieldNomeC.getText() ,jTextFieldCpfC.getText(), jTextFieldDataC.getText(), 
                                 Integer.parseInt(jTextFieldIdC.getText()), jTextFieldDesdeC.getText());
            
            ca.setId_cliente(Integer.parseInt(jTextFieldIdC.getText()));
            ca.setData_cliente(jTextFieldDesdeC.getText());
            ca.setPlaca(jTextFieldPlaca.getText());
            ca.setModelo(jTextFieldModelo.getText());
            ca.setCor(jTextFieldCor.getText());
            
            String palavra = ca.getNome()+","+ca.getCpf()+","+ca.getData_nascimento()+","+ca.getId_cliente()+","+ca.getData_cliente()+","
                            +ca.getPlaca()+","+ca.getModelo()+","+ca.getCor()+",";
            
            ma.escritor(palavra, 2);
            
            tabelaCliente();
            
            jTextFieldNomeC.setText("");
            jTextFieldCpfC.setText("");
            jTextFieldDataC.setText("");
            jTextFieldIdC.setText("");
            jTextFieldDesdeC.setText("");
            jTextFieldPlaca.setText("");
            jTextFieldModelo.setText("");
            jTextFieldCor.setText("");
            
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jButtonListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarFuncionarioActionPerformed
        try {
            tabelaFuncionario();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonListarFuncionarioActionPerformed

    private void jButtonListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarClienteActionPerformed
        try {
            tabelaCliente();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonListarClienteActionPerformed

    private void jButtonSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarClienteActionPerformed
         String nome = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 0);
         String cpf = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 1);
         
         jLabelCliente.setText(nome);
         jLabelCpf.setText(cpf);
    }//GEN-LAST:event_jButtonSelecionarClienteActionPerformed

    private void jButtonSelecionarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarFuncionarioActionPerformed
        String nome = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 0);
         String cargo = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 3);
         
         jLabelFuncionario.setText(nome);
         jLabelCargo.setText(cargo);
    }//GEN-LAST:event_jButtonSelecionarFuncionarioActionPerformed

    private void jButtonGerarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarOrdemActionPerformed
        if( jLabelFuncionario.getText().isEmpty() || jLabelCargo.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Selecione o funcionário que irá realizar o serviço");
        if( jLabelCliente.getText().isEmpty() || jLabelCpf.getText().isEmpty() )
            JOptionPane.showMessageDialog(rootPane, "Selecione o cliente ao qual será realizado o serviço");
        if ( jTextFieldDefeito.getText().isEmpty() )
            JOptionPane.showMessageDialog(rootPane, "Preencha a descrição do defeito e se foi solucionado");
        if ( jTextFieldPecas.getText().isEmpty() || jTextFieldServico.getText().isEmpty() || jTextFieldDesconto.getText().isEmpty() )
            JOptionPane.showMessageDialog(rootPane, "Preencha os valores da ordem de serviço");        
        else {
            
         String nome = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 0);  
         String cpf = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 1);
         String modelo = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 6);
         String placa = (String) jTableLista.getValueAt(jTableLista.getSelectedRow(), 5);
         
         String funcionario = jLabelFuncionario.getText();
         String cargo = jLabelCargo.getText();
         
         String defeito = jTextFieldDefeito.getText();
         String solucionado = jComboBoxSolucionado.getSelectedItem().toString();
         
         String valorPecas = jTextFieldPecas.getText();
         String valorServico = jTextFieldServico.getText();
         String valorDesconto = jTextFieldDesconto.getText();
         String valorTotal = jLabelValorTotal.getText();
                 
        FrmOrdemDeServico frm = new FrmOrdemDeServico();
        frm.dados(nome, cpf, modelo, placa, funcionario, cargo, defeito, solucionado, valorPecas, valorServico, valorDesconto, valorTotal);
        frm.setVisible(true);
        
        }
    }//GEN-LAST:event_jButtonGerarOrdemActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        Calcular calcular = new Calcular();
        jLabelValorTotal.setText( String.valueOf(
            calcular.valorTotal(Integer.parseInt(jTextFieldPecas.getText()), Integer.parseInt(jTextFieldServico.getText()), Integer.parseInt(jTextFieldDesconto.getText()))
        ));
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonListarOrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarOrdemActionPerformed
        try {
            tabelaOrdemDeServico();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonListarOrdemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa().setVisible(true);
            }
        });
    }
    
    public void tabelaCliente() throws IOException {
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Nome", "CPF", "Data Nascimento", "Id Cliente", "Desde", "Placa", "Modelo", "Cor"};
        
        try (FileReader fr = new FileReader("cliente.txt"); BufferedReader br = new BufferedReader(fr)) {
                while(br.ready()){
                    String[] dado = br.readLine().split(",");                     
                    
                        for(int i=0; i<dado.length;i+=8) {

                            dados.add(new Object[] 
                            {dado[0+i], dado[1+i], dado[2+i], dado[3+i], dado[4+i], dado[5+i], dado[6+i], dado[7+i]}
                            );                    

                        } 
                        
                }            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Não foram encontrados dados a serem preenchidos na\nTabela de Clientes!");
            }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableLista.setModel(modelo);
        jTableLista.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableLista.getColumnModel().getColumn(0).setResizable(false);
        jTableLista.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(1).setResizable(false);
        jTableLista.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableLista.getColumnModel().getColumn(2).setResizable(false);
        jTableLista.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableLista.getColumnModel().getColumn(3).setResizable(false);
        jTableLista.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(4).setResizable(false);
        jTableLista.getColumnModel().getColumn(5).setPreferredWidth(60);
        jTableLista.getColumnModel().getColumn(5).setResizable(false);
        jTableLista.getColumnModel().getColumn(6).setPreferredWidth(60);
        jTableLista.getColumnModel().getColumn(6).setResizable(false);
        jTableLista.getColumnModel().getColumn(7).setPreferredWidth(60);
        jTableLista.getColumnModel().getColumn(7).setResizable(false);
        jTableLista.getTableHeader().setReorderingAllowed(false);
        jTableLista.setAutoResizeMode(jTableLista.AUTO_RESIZE_OFF);
        jTableLista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    public void tabelaFuncionario() throws IOException {
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Nome", "CPF", "Data Nascimento", "Cargo", "Desde"};
        
        try (FileReader fr = new FileReader("funcionario.txt"); BufferedReader br = new BufferedReader(fr)) {
                while(br.ready()){
                    String[] dado = br.readLine().split(",");                     
                    
                        for(int i=0; i<dado.length;i+=5) {

                            dados.add(new Object[] 
                            {dado[0+i], dado[1+i], dado[2+i], dado[3+i], dado[4+i]}
                            );                    

                        } 
                        
                }            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Não foram encontrados dados a serem preenchidos na\nTabela de Funcionários!");
            }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableLista.setModel(modelo);
        jTableLista.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableLista.getColumnModel().getColumn(0).setResizable(false);
        jTableLista.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(1).setResizable(false);
        jTableLista.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableLista.getColumnModel().getColumn(2).setResizable(false);
        jTableLista.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableLista.getColumnModel().getColumn(3).setResizable(false);
        jTableLista.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(4).setResizable(false);
        jTableLista.getTableHeader().setReorderingAllowed(false);
        jTableLista.setAutoResizeMode(jTableLista.AUTO_RESIZE_OFF);
        jTableLista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    public void tabelaOrdemDeServico() throws IOException {
        ArrayList dados = new ArrayList();
        
        String[] Colunas = new String[]{"Cliente", "CPF", "Modelo", "Placa", "Funcionario", "Cargo", "Defeito", "Solucionado", "Valor Peça", "Valor Mão de Obra", "Valor Desconto", "Valor Total"};
        
        try (FileReader fr = new FileReader("servico.txt"); BufferedReader br = new BufferedReader(fr)) {
                while(br.ready()){
                    String[] dado = br.readLine().split(",");                     
                    
                        for(int i=0; i<dado.length;i+=12) {

                            dados.add(new Object[] 
                            {dado[0+i], dado[1+i], dado[2+i], dado[3+i], dado[4+i], dado[5+i], dado[6+i], dado[7+i],
                            dado[8+i], dado[9+i], dado[10+i], dado[11+i],}
                            );                    

                        } 
                        
                }            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex);
            }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableLista.setModel(modelo);
        jTableLista.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTableLista.getColumnModel().getColumn(0).setResizable(false);
        jTableLista.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(1).setResizable(false);
        jTableLista.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableLista.getColumnModel().getColumn(2).setResizable(false);
        jTableLista.getColumnModel().getColumn(3).setPreferredWidth(60);
        jTableLista.getColumnModel().getColumn(3).setResizable(false);
        jTableLista.getColumnModel().getColumn(4).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(4).setResizable(false);
        jTableLista.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(5).setResizable(false);
        jTableLista.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableLista.getColumnModel().getColumn(6).setResizable(false);
        jTableLista.getColumnModel().getColumn(7).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(7).setResizable(false);
        jTableLista.getColumnModel().getColumn(8).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(8).setResizable(false);
        jTableLista.getColumnModel().getColumn(9).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(9).setResizable(false);
        jTableLista.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(10).setResizable(false);
        jTableLista.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTableLista.getColumnModel().getColumn(11).setResizable(false);
        jTableLista.getTableHeader().setReorderingAllowed(false);
        jTableLista.setAutoResizeMode(jTableLista.AUTO_RESIZE_OFF);
        jTableLista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonCadastrarFuncionario;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonGerarOrdem;
    private javax.swing.JButton jButtonListarCliente;
    private javax.swing.JButton jButtonListarFuncionario;
    private javax.swing.JButton jButtonListarOrdem;
    private javax.swing.JButton jButtonSelecionarCliente;
    private javax.swing.JButton jButtonSelecionarFuncionario;
    private javax.swing.JComboBox jComboBoxSolucionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelFuncionario;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLista;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldCpfC;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldDataC;
    private javax.swing.JTextField jTextFieldDefeito;
    private javax.swing.JTextField jTextFieldDesconto;
    private javax.swing.JTextField jTextFieldDesde;
    private javax.swing.JTextField jTextFieldDesdeC;
    private javax.swing.JTextField jTextFieldIdC;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeC;
    private javax.swing.JTextField jTextFieldPecas;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldServico;
    // End of variables declaration//GEN-END:variables
}